name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            git clone https://github.com/microsoft/vcpkg
            ./vcpkg/bootstrap-vcpkg.sh
            ./vcpkg/vcpkg install sdl2
          elif [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libsdl2-dev
          fi
      - name: Build
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            gcc -o Chip8Interpreter src/*.c -Ivcpkg\installed\x64-windows\include -lSDL2 -lm
          else
            gcc -o Chip8Interpreter src/*.c -lSDL2 -lm
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Chip8Interpreter-${{ matrix.os }}
          path: Chip8Interpreter
