name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            choco install sdl2
          elif [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libsdl2-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install sdl2
          fi
      - name: Build
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            gcc -o Chip8Interpreter src/*.c -I/mingw64/include/SDL2 -lSDL2 -lm
          else
            gcc -o Chip8Interpreter src/*.c -lSDL2 -lm
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Chip8Interpreter-${{ runner.os }}
          path: ./Chip8Interpreter
